// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFR2vvPUl3F4JXppTOs0Tk5o0YxMfQQI0',
    appId: '1:849708231573:web:091bdd2ea5b04c0ca9a49c',
    messagingSenderId: '849708231573',
    projectId: 'daily-wages-f6c5d',
    authDomain: 'daily-wages-f6c5d.firebaseapp.com',
    storageBucket: 'daily-wages-f6c5d.appspot.com',
    measurementId: 'G-KJQC9MBTTD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1rPau4Ipae2LiuApGYsNvo0HoCJ6U2qg',
    appId: '1:849708231573:android:bffc6a151e262ac8a9a49c',
    messagingSenderId: '849708231573',
    projectId: 'daily-wages-f6c5d',
    storageBucket: 'daily-wages-f6c5d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4ILRmkU0rSEVN01I8zZzfGOjNdLDQSZA',
    appId: '1:849708231573:ios:113d0c0b09c3985ca9a49c',
    messagingSenderId: '849708231573',
    projectId: 'daily-wages-f6c5d',
    storageBucket: 'daily-wages-f6c5d.appspot.com',
    iosBundleId: 'com.example.dailyWage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4ILRmkU0rSEVN01I8zZzfGOjNdLDQSZA',
    appId: '1:849708231573:ios:4b9922a5aad083b6a9a49c',
    messagingSenderId: '849708231573',
    projectId: 'daily-wages-f6c5d',
    storageBucket: 'daily-wages-f6c5d.appspot.com',
    iosBundleId: 'com.example.dailyWage.RunnerTests',
  );
}
